//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto7_MVC_CRUD_DiplomadoUASD.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal Sueldo { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
